import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import './globals.css'

const inter = Sora({ subsets: ['latin'], weight:["200", "400", "600"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
